In [6]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from  sklearn.preprocessing import LabelEncoder

In [9]:
cars_data=pd.read_csv("Cardetails.csv")
cars_data.head(10)

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,torque,seats
0,Maruti Swift Dzire VDI,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.4 kmpl,1248 CC,74 bhp,190Nm@ 2000rpm,5.0
1,Skoda Rapid 1.5 TDI Ambition,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14 kmpl,1498 CC,103.52 bhp,250Nm@ 1500-2500rpm,5.0
2,Honda City 2017-2020 EXi,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.7 kmpl,1497 CC,78 bhp,"12.7@ 2,700(kgm@ rpm)",5.0
3,Hyundai i20 Sportz Diesel,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.0 kmpl,1396 CC,90 bhp,22.4 kgm at 1750-2750rpm,5.0
4,Maruti Swift VXI BSIII,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.1 kmpl,1298 CC,88.2 bhp,"11.5@ 4,500(kgm@ rpm)",5.0
5,Hyundai Xcent 1.2 VTVT E Plus,2017,440000,45000,Petrol,Individual,Manual,First Owner,20.14 kmpl,1197 CC,81.86 bhp,113.75nm@ 4000rpm,5.0
6,Maruti Wagon R LXI DUO BSIII,2007,96000,175000,LPG,Individual,Manual,First Owner,17.3 km/kg,1061 CC,57.5 bhp,"7.8@ 4,500(kgm@ rpm)",5.0
7,Maruti 800 DX BSII,2001,45000,5000,Petrol,Individual,Manual,Second Owner,16.1 kmpl,796 CC,37 bhp,59Nm@ 2500rpm,4.0
8,Toyota Etios VXD,2011,350000,90000,Diesel,Individual,Manual,First Owner,23.59 kmpl,1364 CC,67.1 bhp,170Nm@ 1800-2400rpm,5.0
9,Ford Figo Diesel Celebration Edition,2013,200000,169000,Diesel,Individual,Manual,First Owner,20.0 kmpl,1399 CC,68.1 bhp,160Nm@ 2000rpm,5.0

In [10]:
cars_data.drop(columns=["torque"],inplace=True)

In [11]:
cars_data.isnull().sum()

name               0
year               0
selling_price      0
km_driven          0
fuel               0
seller_type        0
transmission       0
owner              0
mileage          221
engine           221
max_power        215
seats            221
dtype: int64

In [12]:
cars_data.dropna(inplace=True)

In [13]:
cars_data.duplicated().sum()

np.int64(1189)

In [14]:
cars_data.drop_duplicates(inplace=True)

In [15]:
def splitcarname(car_name):
    car_name=car_name.split(' ')[0]
    return car_name.strip()

In [16]:
def clean_data(value):
    value=value.split(' ')[0]
    value=value.strip()
    if value== '':
        value=0
    return float(value)

In [17]:
cars_data['engine']=cars_data['engine'].apply(clean_data)

In [18]:
cars_data['name']=cars_data['name'].astype(str).str.split(' ').str[0]

In [19]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   object
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   object
 5   seller_type    6718 non-null   object
 6   transmission   6718 non-null   object
 7   owner          6718 non-null   object
 8   mileage        6718 non-null   object
 9   engine         6718 non-null   float64
 10  max_power      6718 non-null   object
 11  seats          6718 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 682.3+ KB

In [20]:
cars_data['max_power']=cars_data['max_power'].apply(clean_data)
cars_data['mileage']=cars_data['mileage'].apply(clean_data)

In [21]:
cars_data['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault', 
                           'Mahindra', 'Tata', 'Chevrolet', 'Datsun', 'Jeep', 'Mercedes-Benz', 
                           'Mitsubishi', 'Audi', 'Volkswagen', 'BMW', 'Nissan', 'Lexus', 
                           'Jaguar', 'Land', 'MG', 'Volvo', 'Daewoo', 'Kia', 'Fiat', 'Force', 
                           'Ambassador', 'Ashok', 'Isuzu', 'Opel'], 
                          [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31], 
                          inplace=True)

C:\Users\USER\AppData\Local\Temp\ipykernel_15196\4167893417.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  cars_data['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',
C:\Users\USER\AppData\Local\Temp\ipykernel_15196\4167893417.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  cars_data['name'].replace(['Maruti', 'Skoda', 'Honda', 'Hyundai', 'Toyota', 'Ford', 'Renault',

In [22]:
le=LabelEncoder()
cars_data['name']=le.fit_transform(cars_data['name'])
display(cars_data.head(10))

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,0,2014,450000,145500,Diesel,Individual,Manual,First Owner,23.40,1248.0,74.00,5.0
1,1,2014,370000,120000,Diesel,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,2,2006,158000,140000,Petrol,Individual,Manual,Third Owner,17.70,1497.0,78.00,5.0
3,3,2010,225000,127000,Diesel,Individual,Manual,First Owner,23.00,1396.0,90.00,5.0
4,0,2007,130000,120000,Petrol,Individual,Manual,First Owner,16.10,1298.0,88.20,5.0
5,3,2017,440000,45000,Petrol,Individual,Manual,First Owner,20.14,1197.0,81.86,5.0
6,0,2007,96000,175000,LPG,Individual,Manual,First Owner,17.30,1061.0,57.50,5.0
7,0,2001,45000,5000,Petrol,Individual,Manual,Second Owner,16.10,796.0,37.00,4.0
8,4,2011,350000,90000,Diesel,Individual,Manual,First Owner,23.59,1364.0,67.10,5.0
9,5,2013,200000,169000,Diesel,Individual,Manual,First Owner,20.00,1399.0,68.10,5.0

In [23]:
le=LabelEncoder()
cars_data['fuel']=le.fit_transform(cars_data['fuel'])
display(cars_data.head(10))

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,0,2014,450000,145500,1,Individual,Manual,First Owner,23.40,1248.0,74.00,5.0
1,1,2014,370000,120000,1,Individual,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,2,2006,158000,140000,3,Individual,Manual,Third Owner,17.70,1497.0,78.00,5.0
3,3,2010,225000,127000,1,Individual,Manual,First Owner,23.00,1396.0,90.00,5.0
4,0,2007,130000,120000,3,Individual,Manual,First Owner,16.10,1298.0,88.20,5.0
5,3,2017,440000,45000,3,Individual,Manual,First Owner,20.14,1197.0,81.86,5.0
6,0,2007,96000,175000,2,Individual,Manual,First Owner,17.30,1061.0,57.50,5.0
7,0,2001,45000,5000,3,Individual,Manual,Second Owner,16.10,796.0,37.00,4.0
8,4,2011,350000,90000,1,Individual,Manual,First Owner,23.59,1364.0,67.10,5.0
9,5,2013,200000,169000,1,Individual,Manual,First Owner,20.00,1399.0,68.10,5.0

In [24]:
le=LabelEncoder()
cars_data['seller_type']=le.fit_transform(cars_data['seller_type'])
display(cars_data.head(10))

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,0,2014,450000,145500,1,1,Manual,First Owner,23.40,1248.0,74.00,5.0
1,1,2014,370000,120000,1,1,Manual,Second Owner,21.14,1498.0,103.52,5.0
2,2,2006,158000,140000,3,1,Manual,Third Owner,17.70,1497.0,78.00,5.0
3,3,2010,225000,127000,1,1,Manual,First Owner,23.00,1396.0,90.00,5.0
4,0,2007,130000,120000,3,1,Manual,First Owner,16.10,1298.0,88.20,5.0
5,3,2017,440000,45000,3,1,Manual,First Owner,20.14,1197.0,81.86,5.0
6,0,2007,96000,175000,2,1,Manual,First Owner,17.30,1061.0,57.50,5.0
7,0,2001,45000,5000,3,1,Manual,Second Owner,16.10,796.0,37.00,4.0
8,4,2011,350000,90000,1,1,Manual,First Owner,23.59,1364.0,67.10,5.0
9,5,2013,200000,169000,1,1,Manual,First Owner,20.00,1399.0,68.10,5.0

In [25]:
le=LabelEncoder()
cars_data['owner']=le.fit_transform(cars_data['owner'])
display(cars_data.head(10))

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,0,2014,450000,145500,1,1,Manual,0,23.40,1248.0,74.00,5.0
1,1,2014,370000,120000,1,1,Manual,2,21.14,1498.0,103.52,5.0
2,2,2006,158000,140000,3,1,Manual,4,17.70,1497.0,78.00,5.0
3,3,2010,225000,127000,1,1,Manual,0,23.00,1396.0,90.00,5.0
4,0,2007,130000,120000,3,1,Manual,0,16.10,1298.0,88.20,5.0
5,3,2017,440000,45000,3,1,Manual,0,20.14,1197.0,81.86,5.0
6,0,2007,96000,175000,2,1,Manual,0,17.30,1061.0,57.50,5.0
7,0,2001,45000,5000,3,1,Manual,2,16.10,796.0,37.00,4.0
8,4,2011,350000,90000,1,1,Manual,0,23.59,1364.0,67.10,5.0
9,5,2013,200000,169000,1,1,Manual,0,20.00,1399.0,68.10,5.0

In [26]:
le=LabelEncoder()
cars_data['transmission']=le.fit_transform(cars_data['transmission'])
display(cars_data.head(10))

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,0,2014,450000,145500,1,1,1,0,23.40,1248.0,74.00,5.0
1,1,2014,370000,120000,1,1,1,2,21.14,1498.0,103.52,5.0
2,2,2006,158000,140000,3,1,1,4,17.70,1497.0,78.00,5.0
3,3,2010,225000,127000,1,1,1,0,23.00,1396.0,90.00,5.0
4,0,2007,130000,120000,3,1,1,0,16.10,1298.0,88.20,5.0
5,3,2017,440000,45000,3,1,1,0,20.14,1197.0,81.86,5.0
6,0,2007,96000,175000,2,1,1,0,17.30,1061.0,57.50,5.0
7,0,2001,45000,5000,3,1,1,2,16.10,796.0,37.00,4.0
8,4,2011,350000,90000,1,1,1,0,23.59,1364.0,67.10,5.0
9,5,2013,200000,169000,1,1,1,0,20.00,1399.0,68.10,5.0

In [27]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   int64
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   int64
 5   seller_type    6718 non-null   int64
 6   transmission   6718 non-null   int64
 7   owner          6718 non-null   int64
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   float64
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
dtypes: float64(4), int64(8)
memory usage: 682.3 KB

In [28]:
input_data=cars_data.drop(columns=['selling_price'])
output_data=cars_data['selling_price']

In [29]:
x_train,x_test,y_train,y_test=train_test_split(input_data,output_data,test_size=0.2,random_state=42)

In [30]:
#model Creation
model=LinearRegression()

In [31]:
# Train Model
model.fit(x_train,y_train)

LinearRegression()

In [32]:
predict=model.predict(x_test)

In [33]:
print(predict)

[ 780775.29008886  690795.23037969  542960.95337313 ... 1073949.85536157
 -246958.21338397   42306.6043978 ]

In [34]:
x_train.head(1)

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
2804,2,2008,110000,3,1,1,2,17.7,1497.0,78.0,5.0

In [35]:
input_data_model=pd.DataFrame(
    [[5,2022,12000,1,1,1,1,12,99,2494,0]],
    columns=['name','year','km_driven','fuel','seller_type','transmission','owner','mileage','engine','max_power','seats'])

In [36]:
input_data_model

,name,year,km_driven,fuel,seller_type,transmission,owner,mileage,engine,max_power,seats
0,5,2022,12000,1,1,1,1,12,99,2494,0

In [37]:
model.predict(input_data_model)

array([21984664.94118196])

In [38]:
import pickle as pk

In [39]:
pk.dump(model,open('model.pkl','wb'))

In [40]:
cars_data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6718 entries, 0 to 8125
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   name           6718 non-null   int64
 1   year           6718 non-null   int64
 2   selling_price  6718 non-null   int64
 3   km_driven      6718 non-null   int64
 4   fuel           6718 non-null   int64
 5   seller_type    6718 non-null   int64
 6   transmission   6718 non-null   int64
 7   owner          6718 non-null   int64
 8   mileage        6718 non-null   float64
 9   engine         6718 non-null   float64
 10  max_power      6718 non-null   float64
 11  seats          6718 non-null   float64
dtypes: float64(4), int64(8)
memory usage: 682.3 KB